# services/ingestion/providers/opendota/hero_id_map.py
"""OpenDota-специфічний маппінг: official_name → hero_id.

Містить ТІЛЬКИ ідентифікатори — жодних scores, ролей чи мети.
Мета-дані живуть в domains/heroes/meta.py і є universal.

hero_id верифіковані через https://www.opendota.com/heroes/{id}
'Largo' — підтверджено id=155 (opendota.com/heroes/155).
'Kez' — підтверджено id=145 (opendota.com/heroes/145).
Інші ID верифіковані через OpenDota /heroes endpoint.
"""

OPENDOTA_HERO_IDS: dict[str, int] = {
    "Abaddon":            102,
    "Alchemist":           73,
    "Ancient Apparition":  68,
    "Anti-Mage":            1,
    "Arc Warden":         113,
    "Axe":                  2,
    "Bane":                 3,
    "Batrider":            65,
    "Beastmaster":         38,
    "Bloodseeker":          4,
    "Bounty Hunter":       62,
    "Brewmaster":         118,
    "Bristleback":         99,
    "Broodmother":         54,
    "Centaur Warrunner":   96,
    "Chaos Knight":        81,
    "Chen":                66,
    "Clinkz":              56,
    "Clockwerk":           51,
    "Crystal Maiden":       5,
    "Dark Seer":           55,
    "Dark Willow":        119,
    "Dawnbreaker":        135,
    "Dazzle":              50,
    "Death Prophet":       43,
    "Disruptor":           87,
    "Doom":                69,
    "Dragon Knight":       49,
    "Drow Ranger":          6,
    "Earth Spirit":       107,
    "Earthshaker":          7,
    "Elder Titan":        103,
    "Ember Spirit":       106,
    "Enchantress":         58,
    "Enigma":              33,
    "Faceless Void":       41,
    "Grimstroke":         110,
    "Gyrocopter":          72,
    "Hoodwink":           123,
    "Huskar":              59,
    "Invoker":             74,
    "Io":                  91,
    "Jakiro":              64,
    "Juggernaut":           8,
    "Keeper of the Light": 90,
    "Kez":                145,
    "Kunkka":              23,
    "Largo":              155,
    "Legion Commander":    77,
    "Leshrac":             52,
    "Lich":                31,
    "Lifestealer":         57,
    "Lina":                25,
    "Lion":                26,
    "Lone Druid":          80,
    "Luna":                48,
    "Lycan":               60,
    "Magnus":              97,
    "Marci":              136,
    "Mars":               129,
    "Medusa":              94,
    "Meepo":               82,
    "Mirana":               9,
    "Monkey King":        114,
    "Morphling":           10,
    "Muerta":             138,
    "Naga Siren":          89,
    "Nature's Prophet":    53,
    "Necrophos":           36,
    "Night Stalker":       88,
    "Nyx Assassin":        61,
    "Ogre Magi":           84,
    "Omniknight":          85,
    "Oracle":             111,
    "Outworld Devourer":   76,
    "Pangolier":          120,
    "Phantom Assassin":    44,
    "Phantom Lancer":      12,
    "Phoenix":             78,
    "Primal Beast":       137,
    "Puck":                13,
    "Pudge":               14,
    "Pugna":               45,
    "Queen of Pain":       39,
    "Razor":               15,
    "Riki":                32,
    "Ringmaster":         131,
    "Rubick":              86,
    "Sand King":           16,
    "Shadow Demon":        79,
    "Shadow Fiend":        11,
    "Shadow Shaman":       27,
    "Silencer":            75,
    "Skywrath Mage":      101,
    "Slardar":             28,
    "Slark":               93,
    "Snapfire":           128,
    "Sniper":              35,
    "Spectre":             67,
    "Spirit Breaker":      71,
    "Storm Spirit":        17,
    "Sven":                18,
    "Techies":            105,
    "Templar Assassin":    46,
    "Terrorblade":        109,
    "Tidehunter":          29,
    "Timbersaw":           98,
    "Tinker":              34,
    "Tiny":                19,
    "Treant Protector":    83,
    "Troll Warlord":       95,
    "Tusk":               100,
    "Underlord":          108,
    "Undying":            104,
    "Ursa":                70,
    "Vengeful Spirit":     20,
    "Venomancer":          40,
    "Viper":               47,
    "Visage":              92,
    "Void Spirit":        126,
    "Warlock":             37,
    "Weaver":              63,
    "Windranger":          21,
    "Winter Wyvern":      112,
    "Witch Doctor":        30,
    "Wraith King":         42,
    "Zeus":                22,
}


def get_opendota_id(name: str) -> int | None:
    """Повертає OpenDota hero_id за official_name або None."""
    return OPENDOTA_HERO_IDS.get(name)